steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(node_version)"
    displayName: "Install Node.js"

  # workaround for https://github.com/yarnpkg/yarn/issues/6900
  - script: npm install -g yarn@1.12.3
    displayName: "Install Node v4 compatible Yarn"
    condition: eq(variables.node_version, 4)
