os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - 14
  - 12
  - 10
cache:
  yarn: true
  directories:
    - "node_modules"
    - $HOME/Library/Caches/Homebrew # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci/41386136#41386136
